apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
  namespace: default
type: Opaque
data:
  SMTP_USER: cGl1bWF0YXJhLjE5QGdtYWlsLmNvbQ==  # piumatara.19@gmail.com
  SMTP_PASSWORD: QXBOaUp1QW1AMTI=               # ApNiJuAm@12

