apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: default
spec:
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None  # Headless service, useful for StatefulSets
  selector:
    app: mysql
