apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: "QXBNaUp1QW0hMTI="       # 'ApMiJuAm!12'
  MYSQL_DATABASE: "bW9vbl9kYXRhYmFzZQ=="         # 'moon_database'
  MYSQL_USER: "bW9vbl91c2Vy"                     # 'moon_user'
  MYSQL_PASSWORD: "bW9vbl91c2VyXzEyMw=="         # 'moon_user_123'

