apiVersion: apps/v1
kind: Deployment
metadata:
  name: integration-service-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: integration-service
      version: blue
  template:
    metadata:
      labels:
        app: integration-service
        version: blue
    spec:
      containers:
        - name: integration-service
          image: anjalie19/integration-service:latest
          ports:
            - containerPort: 5002
